import { headCommitId, headTree } from "@/engine";
import { goals } from "../goals";
import { defineTopic } from "../registry";

const base = ['echo "<h1>My Site</h1>" > index.html', 'echo "h1 { color: hotpink; }" > style.css', "git init", "git add .", 'git commit -m "First version"'];

export const everydayTopic = defineTopic({
  id: "everyday",
  title: "Everyday work",
  emoji: "🔁",
  tagline: "Stage, commit, repeat — the loop you'll use every day",
  theme: "sky",
  levels: [
    {
      id: "daily-loop",
      title: "The daily loop",
      mission: "You just made the headings purple in style.css — it's already changed in your Working directory. Stage that change and commit it. Stage → commit is the loop you'll repeat all day.",
      concept: {
        title: "The loop",
        body: "Working with Git is a simple loop: you change files, git add the changes, then git commit them. Then do it again.",
      },
      setup: [...base, 'echo "h1 { color: purple; }" > style.css'],
      goals: [{ ...goals.staged("style.css", "Stage the change to style.css"), sticky: true }, goals.focusedCommit(["style.css"], "Commit it"), goals.cleanTree("Nothing is left unsaved")],
      hints: ["First move the change into the staging area: git add style.css", 'Then save it as a commit: git commit -m "Purple headings"'],
      solution: ["git add style.css", 'git commit -m "Purple headings"'],
      xp: 35,
    },
    {
      id: "commit-am",
      title: "Two steps in one",
      phase: "practice",
      mission: "index.html has a new welcome line. Since Git already tracks that file, you can stage and commit it with a single command.",
      concept: {
        title: "git commit -a",
        body: "-a stages every file Git already tracks, then commits. Handy for quick edits — but it never picks up brand-new files, so git add is still needed for those.",
      },
      setup: [...base, 'edit index.html "<p>Welcome!</p>"'],
      goals: [
        goals.focusedCommit(["index.html"], "Commit the change to index.html"),
        goals.cleanTree("Nothing is left unsaved"),
      ],
      hints: ["git commit has an option that stages tracked files for you.", 'Type: git commit -am "Add welcome line"'],
      solution: ['git commit -am "Add welcome line"'],
      xp: 35,
    },
    {
      id: "spot-the-difference",
      title: "Spot the difference",
      mission: "Someone changed style.css and you're not sure what they did. Look at the exact changes, then commit them.",
      concept: {
        title: "git diff",
        body: "git diff shows, line by line, what changed but isn't staged yet. Lines starting with + were added, lines with - were removed.",
      },
      setup: [...base, 'echo "h1 { color: teal; }" > style.css'],
      goals: [goals.ranCommand("git diff", "See the changes (git diff)"), goals.focusedCommit(["style.css"], "Commit the change"), goals.cleanTree("Nothing is left unsaved")],
      hints: ["Type git diff to see what changed.", 'Commit it — -a stages changed files for you: git commit -am "Teal headings"'],
      solution: ["git diff", 'git commit -am "Teal headings"'],
      xp: 35,
    },
    {
      id: "one-change-one-commit",
      title: "One change, one commit",
      phase: "practice",
      mission: "You changed style.css and also started a new about.html page. Save them as two separate commits — one for each change.",
      concept: {
        title: "Small commits",
        body: "Focused commits keep history easy to read and easy to undo. Stage only the files for one change, commit, then do the next one.",
      },
      setup: [...base, 'echo "h1 { color: rebeccapurple; }" > style.css', 'echo "<h1>About me</h1>" > about.html'],
      goals: [
        goals.focusedCommit(["style.css"], "Commit style.css on its own"),
        goals.focusedCommit(["about.html"], "Commit about.html on its own"),
        goals.cleanTree("Nothing is left unsaved"),
      ],
      hints: ["Stage just one file: git add style.css — then commit.", "Do the same for about.html: git add about.html, then commit again."],
      solution: ["git add style.css", 'git commit -m "Update colours"', "git add about.html", 'git commit -m "Add about page"'],
      xp: 40,
    },
    {
      id: "ignore-junk",
      title: "Ignore the junk",
      mission: "Your app writes a debug.log file that should never be saved, so there's already a .gitignore file that lists it. Stage everything and commit — and watch debug.log stay out.",
      concept: {
        title: ".gitignore",
        body: "A .gitignore file lists files Git should pretend don't exist — logs, secrets, build output. Ignored files never show up as new files to add.",
      },
      setup: [...base, 'echo "start()" > app.js', 'echo "error at line 3" > debug.log', 'echo "debug.log" > .gitignore'],
      goals: [
        goals.committedFile("app.js", "Commit app.js"),
        goals.committedFile(".gitignore", "Commit the .gitignore file too"),
        goals.custom(
          "log-left-out",
          "debug.log stays out of the commit",
          ({ state, initial }) => state.initialized && headCommitId(state) !== headCommitId(initial) && !Object.hasOwn(headTree(state), "debug.log"),
        ),
      ],
      hints: ["git add . stages every file — except the ones listed in .gitignore.", 'Stage and commit: git add . then git commit -m "Add app"'],
      solution: ["git add .", 'git commit -m "Add app"'],
      xp: 45,
    },
    {
      id: "delete-a-file",
      title: "Delete a file",
      mission: "old-page.html isn't needed any more. Remove it from the project and commit the deletion.",
      concept: {
        title: "git rm",
        body: "git rm deletes a file and stages the deletion in one step. The next commit records that the file is gone.",
      },
      setup: [...base, 'echo "<h1>Old</h1>" > old-page.html', "git add .", 'git commit -m "Add old page"'],
      goals: [
        goals.absentFromHead("old-page.html", "old-page.html is gone from the latest commit"),
        goals.custom("file-gone", "…and from the folder", ({ state }) => !Object.hasOwn(state.workdir, "old-page.html")),
        goals.cleanTree("Nothing is left unsaved"),
      ],
      hints: ["git rm deletes the file and stages that deletion.", 'git rm old-page.html, then git commit -m "Remove old page"'],
      solution: ["git rm old-page.html", 'git commit -m "Remove old page"'],
      xp: 40,
    },
    {
      id: "rename-a-file",
      title: "Rename a file",
      phase: "practice",
      mission: "The homepage should be called home.html, not index.html. Rename it so Git records the rename, then commit.",
      concept: {
        title: "git mv",
        body: "git mv does two things at once: it renames the file on disk and stages the rename. Renaming by hand would look to Git like one file deleted and another added.",
      },
      setup: [...base],
      goals: [
        goals.committedFile("home.html", "home.html is committed"),
        goals.absentFromHead("index.html", "index.html is gone"),
        goals.cleanTree("Nothing is left unsaved"),
      ],
      hints: ["git mv takes the old name and the new one.", 'git mv index.html home.html, then git commit -m "Rename homepage"'],
      solution: ["git mv index.html home.html", 'git commit -m "Rename homepage"'],
      xp: 45,
    },
    {
      id: "stop-tracking",
      title: "Stop tracking a file",
      phase: "practice",
      mission: "secrets.env was committed by mistake and is now listed in .gitignore. Take it out of Git's hands — keep the file on disk, but make the next commit forget it.",
      concept: {
        title: "git rm --cached",
        body: "git rm deletes the file too; git rm --cached only removes it from Git, leaving your copy alone. With the name in .gitignore, Git then ignores it for good.",
      },
      setup: [
        ...base,
        'echo "API_KEY=123" > secrets.env',
        "git add .",
        'git commit -m "Add config"',
        'echo "secrets.env" > .gitignore',
        "git add .gitignore",
        'git commit -m "Ignore secret files"',
      ],
      goals: [
        goals.absentFromHead("secrets.env", "secrets.env is gone from the latest commit"),
        goals.custom("kept-on-disk", "…but still on your disk", ({ state }) => Object.hasOwn(state.workdir, "secrets.env")),
        goals.cleanTree("Nothing is left unsaved"),
      ],
      hints: ["Remove it from Git but keep the file: git rm --cached secrets.env", 'Then commit that removal: git commit -m "Stop tracking secrets"'],
      solution: ["git rm --cached secrets.env", 'git commit -m "Stop tracking secrets"'],
      xp: 50,
    },
    {
      id: "rename-again",
      title: "Rename the stylesheet",
      phase: "practice",
      mission: "The team renames stylesheets to main.css. Rename style.css and commit — two commands, same pair you used for the homepage.",
      concept: {
        title: "Renames are cheap",
        body: "Because Git stores snapshots, a rename is just a delete plus an add — git mv does both and stages them for you.",
      },
      setup: [...base],
      goals: [
        goals.committedFile("main.css", "main.css is committed"),
        goals.absentFromHead("style.css", "style.css is gone"),
        goals.cleanTree("Nothing is left unsaved"),
      ],
      hints: ["git mv style.css main.css", 'Then git commit -m "Rename stylesheet"'],
      solution: ["git mv style.css main.css", 'git commit -m "Rename stylesheet"'],
      xp: 45,
    },
    {
      id: "spring-clean",
      title: "Spring clean",
      phase: "practice",
      mission: "Two jobs in one tidy-up: the old about-us.html page should go, and contact.htm is missing its 'l'. Delete one, rename the other, and commit the lot.",
      concept: {
        title: "rm and mv together",
        body: "git rm and git mv both change files and stage that change in one step, so a tidy-up is just those commands followed by a single commit.",
      },
      setup: [...base, 'echo "<h1>About us</h1>" > about-us.html', 'echo "<h1>Contact</h1>" > contact.htm', "git add .", 'git commit -m "Add pages"'],
      goals: [
        goals.absentFromHead("about-us.html", "about-us.html is gone"),
        goals.committedFile("contact.html", "contact.html has the right name"),
        goals.absentFromHead("contact.htm", "…and the typo name is gone"),
        goals.cleanTree("Nothing is left unsaved"),
      ],
      hints: ["Delete one: git rm about-us.html", 'Rename the other: git mv contact.htm contact.html, then git commit -m "Tidy pages"'],
      solution: ["git rm about-us.html", "git mv contact.htm contact.html", 'git commit -m "Tidy pages"'],
      xp: 50,
    },
    {
      id: "checkpoint-everyday",
      title: "Checkpoint: a tidy day's work",
      phase: "checkpoint",
      mission:
        "A normal day: the stylesheet changed, there's a new pricing page, and your app left a debug.log behind (already ignored). Save the two real changes as two separate commits and finish with nothing unsaved.",
      concept: {
        title: "Putting it together",
        body: "Look at what changed, stage one idea at a time, commit it, repeat. Ignored files stay out of your way the whole time.",
      },
      setup: [...base, 'echo "debug.log" > .gitignore', "git add .gitignore", 'git commit -m "Ignore logs"', 'echo "h1 { color: navy; }" > style.css', 'echo "<h1>Pricing</h1>" > pricing.html', 'echo "crash at line 9" > debug.log'],
      goals: [
        goals.focusedCommit(["style.css"], "One commit for the stylesheet"),
        goals.focusedCommit(["pricing.html"], "Another for the pricing page"),
        goals.custom("log-left-out", "debug.log is never committed", ({ state }) => state.initialized && !Object.hasOwn(headTree(state), "debug.log")),
        goals.cleanTree("Nothing is left unsaved"),
      ],
      hints: ["Handle one change at a time: git add style.css, then commit it.", 'Then the new page: git add pricing.html, then git commit -m "Add pricing page". The log is ignored, so git status never mentions it.'],
      solution: ["git add style.css", 'git commit -m "Navy headings"', "git add pricing.html", 'git commit -m "Add pricing page"'],
      xp: 55,
    },
  ],
});
