import { headTree } from "@/engine";
import { goals } from "../goals";
import { defineTopic } from "../registry";

const shop = ['echo "# Shop" > README.md', "git init", "git add .", 'git commit -m "Initial commit"'];

export const rewriteTopic = defineTopic({
  id: "rewrite",
  title: "Rewrite history",
  emoji: "✨",
  tagline: "Copy, move and tidy commits",
  theme: "fuchsia",
  levels: [
    {
      id: "cherry-pick",
      title: "Cherry-pick a commit",
      mission: "The experiment branch is mostly chaos, but one commit — 'Fix header bug' — is gold. Copy just that commit onto main.",
      concept: {
        title: "git cherry-pick",
        body: "cherry-pick copies the changes from one commit onto the branch you're on, as a brand-new commit.",
      },
      setup: [
        'echo "<header>Shpo</header>" > header.html',
        "git init",
        "git add .",
        'git commit -m "Initial commit"',
        "git switch -c experiment",
        'echo "spin()" > wild.js',
        "git add .",
        'git commit -m "Wild idea"',
        'echo "<header>Shop</header>" > header.html',
        'git commit -am "Fix header bug"',
        'echo "explode()" > crazy.js',
        "git add .",
        'git commit -m "Crazy idea"',
        "git switch main",
      ],
      goals: [
        goals.containsMessage("main", "Fix header bug", "main has 'Fix header bug'"),
        goals.lacksMessage("main", "Wild idea", "…but not 'Wild idea'"),
        goals.lacksMessage("main", "Crazy idea", "…and not 'Crazy idea'"),
      ],
      hints: ["'Fix header bug' is one commit before the tip of experiment: experiment~1.", "Type: git cherry-pick experiment~1"],
      solution: ["git cherry-pick experiment~1"],
      xp: 75,
    },
    {
      id: "cherry-pick-by-id",
      title: "Cherry-pick by id",
      phase: "practice",
      mission: "A designer's branch has three commits, and you only want 'Fix the logo' — the middle one. Look up its id in the history, then copy just that commit onto main.",
      concept: {
        title: "Commits have names",
        body: "Any commit can be named by its id, a branch name, or something like design~1. Use git log to find the id, then hand it to cherry-pick.",
      },
      setup: [
        ...shop,
        "git switch -c design",
        'echo "big()" > banner.css',
        "git add .",
        'git commit -m "Giant banner"',
        'echo "logo()" > logo.svg',
        "git add .",
        'git commit -m "Fix the logo"',
        'echo "rainbow()" > rainbow.css',
        "git add .",
        'git commit -m "Rainbow everything"',
        "git switch main",
      ],
      goals: [
        goals.committedFile("logo.svg", "main has the logo fix"),
        goals.lacksMessage("main", "Giant banner", "…but not the giant banner"),
        goals.lacksMessage("main", "Rainbow everything", "…and not the rainbows"),
        goals.onBranch("main", "You're still on main"),
      ],
      hints: ["Find the id first: git log --oneline design", "Then copy it: git cherry-pick <id> (design~1 works too)"],
      solution: ["git log --oneline design", "git cherry-pick {{rev:design~1}}"],
      xp: 80,
    },
    {
      id: "rebase",
      title: "Straighten the line",
      mission: "Your search branch started a while ago and main has moved on since. Rebase search onto main so its commits sit on top — one straight line, no merge commit.",
      concept: {
        title: "git rebase",
        body: "rebase replays your branch's commits one by one on top of another branch, making fresh copies. Only rebase commits you haven't shared.",
      },
      setup: [
        ...shop,
        "git switch -c search",
        'echo "searchBox()" > search.js',
        "git add .",
        'git commit -m "Add search box"',
        'edit search.js "showResults()"',
        'git commit -am "Show search results"',
        "git switch main",
        'echo "<h1>News</h1>" > news.html',
        "git add .",
        'git commit -m "Add news page"',
      ],
      goals: [
        goals.basedOn("search", "main", "search starts from the tip of main"),
        goals.linearHistory("search", "search is one straight line"),
        goals.containsMessage("search", "Show search results", "search still has its own commits"),
      ],
      hints: ["Rebase moves the branch you're on, so go there first: git switch search", "Then replay it on top of main: git rebase main"],
      solution: ["git switch search", "git rebase main"],
      xp: 85,
    },
    {
      id: "rebase-then-merge",
      title: "Rebase, then hand it over",
      phase: "practice",
      mission: "Finish the filters branch the tidy way: replay it on top of main, then bring it into main. Because it now sits directly on top, main just slides forward — no merge commit, one straight history.",
      concept: {
        title: "Rebase then fast-forward",
        body: "Rebasing first means the merge has nothing to combine, so Git can simply move the label. This is how teams keep history a straight line.",
      },
      setup: [
        ...shop,
        "git switch -c filters",
        'echo "filterByPrice()" > filters.js',
        "git add .",
        'git commit -m "Add price filter"',
        "git switch main",
        'echo "<h1>Sale</h1>" > sale.html',
        "git add .",
        'git commit -m "Add sale page"',
        "git switch filters",
      ],
      goals: [
        goals.onBranch("main", "End up on main"),
        goals.containsMessage("main", "Add price filter", "main has the filter work"),
        goals.linearHistory("main", "main is one straight line (no merge commit)"),
        goals.committedFile("sale.html", "The sale page is still there"),
      ],
      hints: ["First replay your branch on top of main: git rebase main", "Then hand it over: git switch main, then git merge filters"],
      solution: ["git rebase main", "git switch main", "git merge filters"],
      xp: 85,
    },
    {
      id: "squash",
      title: "Squash commits",
      mission: "Three messy 'WIP' commits clutter your history. Combine them into one clean commit called 'Add search' — keeping all the changes.",
      concept: {
        title: "Squashing",
        body: "Squashing turns several small commits into one. A simple way: reset --soft back past them (the changes stay staged), then commit once.",
      },
      setup: [
        ...shop,
        'echo "searchBox()" > search.js',
        "git add .",
        'git commit -m "WIP 1"',
        'edit search.js "showResults()"',
        'git commit -am "WIP 2"',
        'edit search.js "highlight()"',
        'git commit -am "WIP 3"',
      ],
      goals: [
        goals.tipMessage("main", "Add search", "The last commit is 'Add search'"),
        goals.exactCommitCount("main", 2, "Only 2 commits in total"),
        goals.custom("kept", "All the work is kept", ({ state, initial }) => state.initialized && headTree(state)["search.js"] === headTree(initial)["search.js"]),
      ],
      hints: ["Undo the three commits but keep their changes staged: git reset --soft HEAD~3", 'Then commit them as one: git commit -m "Add search"'],
      solution: ["git reset --soft HEAD~3", 'git commit -m "Add search"'],
      xp: 85,
    },
    {
      id: "cherry-pick-to-branch",
      title: "Take a fix with you",
      phase: "practice",
      mission: "main has a security fix your release branch needs right now — but not the rest of main. You're on release: copy just that one commit over.",
      concept: {
        title: "Cherry-pick works both ways",
        body: "cherry-pick copies a commit onto the branch you're standing on, whichever branch it came from. Ideal for hotfixes that can't wait for a merge.",
      },
      setup: [
        ...shop,
        "git switch -c release",
        'echo "<h1>Shop v1</h1>" > shop.html',
        "git add .",
        'git commit -m "Release page"',
        "git switch main",
        'echo "sanitize()" > security.js',
        "git add .",
        'git commit -m "Fix security hole"',
        'echo "experiment()" > lab.js',
        "git add .",
        'git commit -m "Wild experiment"',
        "git switch release",
      ],
      goals: [
        goals.containsMessage("release", "Fix security hole", "release has the security fix"),
        goals.lacksMessage("release", "Wild experiment", "…but not the experiment"),
        goals.onBranch("release", "You're still on release"),
      ],
      hints: ["The fix is one commit before the tip of main: main~1.", "Type: git cherry-pick main~1"],
      solution: ["git cherry-pick main~1"],
      xp: 80,
    },
    {
      id: "squash-two",
      title: "Squash a pair",
      phase: "practice",
      mission: "Two commits say 'typo' and 'typo again'. Fold them into one commit called 'Fix typos' — same changes, tidier history.",
      concept: {
        title: "Squashing, again",
        body: "reset --soft as far back as you want, then commit once. The number after HEAD~ is how many commits you're folding together.",
      },
      setup: [
        ...shop,
        'echo "<h1>Shpo</h1>" > index.html',
        "git add .",
        'git commit -m "Add homepage"',
        'echo "<h1>Shop</h1>" > index.html',
        'git commit -am "typo"',
        'echo "<h1>Shop</h1><p>Welcome</p>" > index.html',
        'git commit -am "typo again"',
      ],
      goals: [
        goals.tipMessage("main", "Fix typos", "The last commit is 'Fix typos'"),
        goals.exactCommitCount("main", 3, "Three commits in total"),
        goals.custom("kept", "The final text is kept", ({ state, initial }) => state.initialized && headTree(state)["index.html"] === headTree(initial)["index.html"]),
      ],
      hints: ["Fold the last two: git reset --soft HEAD~2", 'Then commit them as one: git commit -m "Fix typos"'],
      solution: ["git reset --soft HEAD~2", 'git commit -m "Fix typos"'],
      xp: 85,
    },
    {
      id: "checkpoint-rewrite",
      title: "Checkpoint: tidy before sharing",
      phase: "checkpoint",
      mission:
        "The gallery branch has two scrappy 'WIP' commits and main has moved on. Clean it up before anyone sees it: squash the two into one commit called 'Add gallery', replay it on top of main, and hand it over to main as a straight line.",
      concept: {
        title: "The tidy-up routine",
        body: "Squash the noise, rebase onto main, then merge. History ends up as one readable line of finished work.",
      },
      setup: [
        ...shop,
        "git switch -c gallery",
        'echo "gallery()" > gallery.js',
        "git add .",
        'git commit -m "WIP gallery"',
        'edit gallery.js "lightbox()"',
        'git commit -am "WIP more gallery"',
        "git switch main",
        'echo "<h1>Team</h1>" > team.html',
        "git add .",
        'git commit -m "Add team page"',
        "git switch gallery",
      ],
      goals: [
        goals.onBranch("main", "End up on main"),
        goals.containsMessage("main", "Add gallery", "main has one 'Add gallery' commit"),
        goals.lacksMessage("main", "WIP gallery", "…and no WIP commits"),
        goals.linearHistory("main", "main is one straight line"),
        goals.custom("kept", "The gallery work is all there", ({ state, initial }) => state.initialized && headTree(state)["gallery.js"] === initial.workdir["gallery.js"]),
      ],
      hints: [
        "Squash first, while you're on gallery: git reset --soft HEAD~2, then git commit -m \"Add gallery\"",
        "Replay it on top of main: git rebase main",
        "Then hand it over: git switch main, then git merge gallery",
      ],
      solution: ["git reset --soft HEAD~2", 'git commit -m "Add gallery"', "git rebase main", "git switch main", "git merge gallery"],
      xp: 95,
    },
  ],
});
