import { goals } from "../goals";
import { defineTopic } from "../registry";

const initial = ['echo "# Shop" > README.md', "git init", "git add .", 'git commit -m "Initial commit"'];

export const tagsStashTopic = defineTopic({
  id: "tags-stash",
  title: "Tags & stash",
  emoji: "🏷️",
  tagline: "Mark releases and park unfinished work",
  theme: "cyan",
  levels: [
    {
      id: "tag-release",
      title: "Tag a release",
      mission: "The shop is ready to launch! Mark the latest commit with a tag called v1.0.",
      concept: {
        title: "Tags",
        body: "A tag is a permanent name for one commit — perfect for releases like v1.0. Unlike branches, tags never move.",
      },
      setup: [...initial, 'echo "<h1>Shop</h1>" > shop.html', "git add .", 'git commit -m "Ready for launch"'],
      goals: [goals.tagOn("v1.0", "Ready for launch", "Tag the latest commit as v1.0")],
      hints: ["git tag <name> tags the commit you're on.", "Type: git tag v1.0"],
      solution: ["git tag v1.0"],
      xp: 55,
    },
    {
      id: "tag-the-past",
      title: "Tag the past",
      phase: "practice",
      mission: "You forgot to tag the beta. The 'Beta ready' commit is two commits before HEAD. Tag it as v0.9 — without moving anywhere.",
      concept: {
        title: "HEAD~N",
        body: "HEAD~1 is the commit before the current one, HEAD~2 the one before that. Most commands accept these references.",
      },
      setup: [
        ...initial,
        'echo "<h1>Shop</h1>" > shop.html',
        "git add .",
        'git commit -m "Beta ready"',
        'edit shop.html "<p>Now with prices</p>"',
        'git commit -am "Add prices"',
        'edit shop.html "<p>Free shipping</p>"',
        'git commit -am "Add shipping info"',
      ],
      goals: [goals.tagOn("v0.9", "Beta ready", "Tag 'Beta ready' as v0.9"), goals.onBranch("main", "Stay on main")],
      hints: ["Give git tag a second argument: the commit to tag. HEAD~2 is two commits back.", "Type: git tag v0.9 HEAD~2"],
      solution: ["git tag v0.9 HEAD~2"],
      xp: 60,
    },
    {
      id: "retag",
      title: "Move a tag you got wrong",
      phase: "practice",
      mission: "v1.1 ended up on the wrong commit — it's on 'Fix typo' instead of the finished 'Add checkout'. Delete that tag and put v1.1 where it belongs.",
      concept: {
        title: "git tag -d",
        body: "Tags never move on their own, so a mistake is fixed in two steps: delete the tag with git tag -d, then create it again on the right commit. git tag on its own lists them.",
      },
      setup: [
        ...initial,
        'echo "typo fixed" > README.md',
        'git commit -am "Fix typo"',
        "git tag v1.1",
        'echo "checkout()" > checkout.js',
        "git add .",
        'git commit -m "Add checkout"',
      ],
      goals: [goals.tagOn("v1.1", "Add checkout", "v1.1 points at 'Add checkout'")],
      hints: ["First remove the wrong one: git tag -d v1.1", "Then tag the commit you're on: git tag v1.1"],
      solution: ["git tag -d v1.1", "git tag v1.1"],
      xp: 60,
    },
    {
      id: "stash-it",
      title: "Stash it away",
      mission: "You're halfway through a change on feature when your teammate's urgent hotfix has to go into main right now. Stash your unfinished work, merge hotfix into main, then return to feature and bring your work back.",
      concept: {
        title: "git stash",
        body: "git stash packs away unfinished changes and gives you a clean folder. git stash pop unpacks them again, right where you left off.",
      },
      setup: [
        ...initial,
        "git switch -c hotfix",
        'echo "# Shop — now open!" > README.md',
        'git commit -am "Fix opening hours"',
        "git switch main",
        "git switch -c feature",
        'echo "cart()" > cart.js',
        "git add .",
        'git commit -m "Start cart"',
        'edit cart.js "checkout()"',
      ],
      goals: [
        goals.includes("main", "hotfix", "Merge hotfix into main"),
        goals.onBranch("feature", "Come back to feature"),
        goals.custom(
          "work-back",
          "Your unfinished work is back in your folder",
          ({ state, initial: start }) => state.stash.length === 0 && state.workdir["cart.js"] === start.workdir["cart.js"],
        ),
      ],
      hints: [
        "Park your work so you can switch branches: git stash",
        "On main, bring the fix in: git switch main, then git merge hotfix",
        "Go back with git switch feature, then unpack with git stash pop",
      ],
      solution: ["git stash", "git switch main", "git merge hotfix", "git switch feature", "git stash pop"],
      xp: 75,
    },
    {
      id: "stash-pick",
      title: "Pick the right stash",
      phase: "practice",
      mission: "There are two stashes: the newest one is a dead end, but the older one holds the banner work you want. List them, bring back the older one, and throw the dead end away.",
      concept: {
        title: "The stash is a stack",
        body: "Each git stash pushes onto a stack: stash@{0} is the newest. Name the one you want (git stash pop stash@{1}) and drop the ones you don't (git stash drop).",
      },
      setup: [
        ...initial,
        'echo "<aside>Banner</aside>" > banner.html',
        "git add .",
        'git commit -m "Add banner"',
        'edit banner.html "<aside>Summer sale banner</aside>"',
        "git stash",
        'edit banner.html "<aside>ZZZ dead end</aside>"',
        "git stash",
      ],
      goals: [
        goals.custom("banner-back", "The banner work is back in your folder", ({ state, initial: start }) => state.workdir["banner.html"] === start.stash[1]?.workdir["banner.html"]),
        goals.custom("stash-empty", "Both stashes are cleared out", ({ state }) => state.stash.length === 0),
      ],
      hints: [
        "See what you have first: git stash list",
        "The older one is stash@{1}: git stash pop stash@{1}",
        "Then bin the dead end: git stash drop",
      ],
      solution: ["git stash list", "git stash pop stash@{1}", "git stash drop"],
      xp: 75,
    },
    {
      id: "tag-hotfix",
      title: "Tag the hotfix",
      phase: "practice",
      mission: "A quick fix went out after v1.0. Tag the latest commit as v1.0.1 so the team can point at exactly what shipped.",
      concept: {
        title: "Tags pile up",
        body: "A repository can carry as many tags as you like — one per release. git tag on its own lists them all.",
      },
      setup: [
        ...initial,
        'echo "<h1>Shop</h1>" > shop.html',
        "git add .",
        'git commit -m "Ready for launch"',
        "git tag v1.0",
        'edit shop.html "<p>Fixed the price</p>"',
        'git commit -am "Fix price bug"',
      ],
      goals: [goals.tagOn("v1.0.1", "Fix price bug", "Tag the fix as v1.0.1"), goals.custom("kept-v1", "v1.0 is still there", ({ state }) => Object.hasOwn(state.tags, "v1.0"))],
      hints: ["You're already on the commit that shipped.", "Type: git tag v1.0.1"],
      solution: ["git tag v1.0.1"],
      xp: 60,
    },
    {
      id: "stash-to-pull",
      title: "Stash, pull, carry on",
      phase: "practice",
      mission: "You're mid-edit when a teammate's commit needs pulling in — and Git won't pull over your unsaved change. Park it, pull, then put your work back.",
      concept: {
        title: "Stash before you pull",
        body: "Anything that rewrites your files — pull, switch, checkout — needs a clean folder. Stash is the quickest way to get one and the quickest way back.",
      },
      setup: [
        "server create https://github.com/team/shop",
        'server commit https://github.com/team/shop "Initial commit" --file README.md --content "# Shop"',
        "git clone https://github.com/team/shop",
        'server commit https://github.com/team/shop "Add opening hours" --file hours.md --content "Open 9-5"',
        'edit README.md "My half-written note"',
      ],
      goals: [
        goals.custom(
          "up-to-date",
          "main has the teammate's commit",
          ({ state }) => state.branches.main === state.servers["https://github.com/team/shop"]?.branches.main,
        ),
        goals.committedFile("hours.md", "The opening hours file arrived"),
        goals.custom(
          "work-back",
          "Your unfinished note is back",
          ({ state, initial: start }) => state.stash.length === 0 && state.workdir["README.md"] === start.workdir["README.md"],
        ),
      ],
      hints: ["Park the edit: git stash", "Then git pull, and bring it back with git stash pop"],
      solution: ["git stash", "git pull", "git stash pop"],
      xp: 75,
    },
    {
      id: "tag-cleanup",
      title: "Clear out old tags",
      phase: "practice",
      mission: "Two tags were made by mistake: test-tag and delete-me. Remove both and leave v1.0 alone.",
      concept: {
        title: "Tags are easy to remove",
        body: "git tag -d <name> deletes a tag locally. Nothing about the commits changes — you're only removing a label.",
      },
      setup: [...initial, 'echo "<h1>Shop</h1>" > shop.html', "git add .", 'git commit -m "Ready for launch"', "git tag v1.0", "git tag test-tag", "git tag delete-me"],
      goals: [
        goals.custom("test-gone", "test-tag is gone", ({ state }) => !Object.hasOwn(state.tags, "test-tag")),
        goals.custom("delete-me-gone", "delete-me is gone", ({ state }) => !Object.hasOwn(state.tags, "delete-me")),
        goals.tagOn("v1.0", "Ready for launch", "v1.0 is untouched"),
      ],
      hints: ["Delete them one at a time: git tag -d test-tag", "Then: git tag -d delete-me"],
      solution: ["git tag -d test-tag", "git tag -d delete-me"],
      xp: 60,
    },
    {
      id: "checkpoint-tags-stash",
      title: "Checkpoint: release day",
      phase: "checkpoint",
      mission:
        "Release day, and you're mid-change in shop.html. Before tagging, the team wants you to check the very first version of the shop. Park your unfinished work, visit that first commit, come back to main, tag the release as v2.0, and pick your work up again.",
      concept: {
        title: "Park, look, resume",
        body: "Git won't let you jump to another commit while unsaved changes would be overwritten. Stash gives you the clean folder you need, and pop hands your work straight back.",
      },
      setup: [
        ...initial,
        'echo "<h1>Shop</h1>" > shop.html',
        "git add .",
        'git commit -m "Shop is ready"',
        'edit shop.html "<p>Half-written banner</p>"',
      ],
      goals: [
        goals.custom(
          "visited",
          "Visit the first commit",
          ({ state }) => state.head.kind === "detached" && state.commits[state.head.commit]?.message === "Initial commit",
          true,
        ),
        goals.onBranch("main", "End up back on main"),
        goals.tagOn("v2.0", "Shop is ready", "Tag 'Shop is ready' as v2.0"),
        goals.custom(
          "work-back",
          "Your unfinished work is back",
          ({ state, initial: start }) => state.stash.length === 0 && state.workdir["shop.html"] === start.workdir["shop.html"],
        ),
      ],
      hints: [
        "Your unsaved change is in the way of jumping back, so park it: git stash",
        "Visit the first commit (git checkout HEAD~1), then come home: git switch main",
        "Tag it (git tag v2.0) and get your work back: git stash pop",
      ],
      solution: ["git stash", "git checkout HEAD~1", "git switch main", "git tag v2.0", "git stash pop"],
      xp: 80,
    },
  ],
});
