import { computeStatus, headTree } from "@/engine";
import { goals } from "../goals";
import { defineTopic } from "../registry";

const initial = ['echo "# Shop" > README.md', "git init", "git add .", 'git commit -m "Initial commit"'];

export const undoTopic = defineTopic({
  id: "undo",
  title: "Rollback",
  emoji: "⏪",
  tagline: "Step back from the working directory, the staging area or a commit",
  theme: "amber",
  levels: [
    {
      id: "discard-changes",
      title: "Throw away an edit",
      mission: "You scribbled over README.md by accident. Throw that edit away and get back the last saved version.",
      concept: {
        title: "git restore",
        body: "git restore <file> replaces your edits with the last saved version. Careful: the thrown-away edits are gone for good.",
      },
      setup: [...initial, 'echo "oops, I deleted everything" > README.md'],
      goals: [
        goals.custom("restored", "README.md is back to the saved version", ({ state }) => state.initialized && state.workdir["README.md"] === headTree(state)["README.md"]),
        goals.cleanTree("No leftover changes"),
      ],
      hints: ["git restore brings a file back to its last saved version.", "Type: git restore README.md"],
      solution: ["git restore README.md"],
      xp: 50,
    },
    {
      id: "restore-everything",
      title: "Throw away every edit",
      phase: "practice",
      mission: "A bad find-and-replace wrecked all three files. None of it is worth keeping — bring the whole folder back to the last commit with one command.",
      concept: {
        title: "git restore .",
        body: "The dot means the whole folder, just like with git add. git restore . resets every tracked file to the last saved version at once.",
      },
      setup: [
        ...initial,
        'echo "page()" > app.js',
        'echo "h1 {}" > style.css',
        "git add .",
        'git commit -m "Add app and styles"',
        'echo "ZZZZ" > README.md',
        'echo "ZZZZ" > app.js',
        'echo "ZZZZ" > style.css',
      ],
      goals: [
        goals.cleanTree("Nothing is left changed"),
        goals.custom("all-back", "All three files match the last commit", ({ state }) => {
          const saved = headTree(state);
          return ["README.md", "app.js", "style.css"].every((path) => state.workdir[path] === saved[path]);
        }),
      ],
      hints: ["You don't have to name each file.", "Type: git restore ."],
      solution: ["git restore ."],
      xp: 50,
    },
    {
      id: "unstage",
      title: "Oops, unstage that",
      mission: "You ran git add . too quickly and passwords.txt got staged with app.js. Take passwords.txt out of the staging area (keep the file), but leave app.js staged.",
      concept: {
        title: "Unstaging",
        body: "git restore --staged <file> is the opposite of git add. The file leaves the staging area, but your copy on disk stays untouched.",
      },
      setup: [...initial, "echo \"console.log('hi')\" > app.js", 'echo "hunter2" > passwords.txt', "git add ."],
      goals: [goals.untrackedOnDisk("passwords.txt", "passwords.txt is no longer staged"), goals.staged("app.js", "app.js is still staged")],
      hints: ["You need the opposite of git add, for one file.", "Type: git restore --staged passwords.txt"],
      solution: ["git restore --staged passwords.txt"],
      xp: 50,
    },
    {
      id: "diff-staged",
      title: "Check before you commit",
      phase: "practice",
      mission: "Both files changed, but only the style.css change is ready. Stage style.css, double-check what's about to be committed, and commit only that — index.html keeps its unsaved change.",
      concept: {
        title: "git diff --staged",
        body: "git diff shows what is NOT staged yet; git diff --staged shows what IS staged — exactly what your next commit will contain.",
      },
      setup: [
        ...initial,
        'echo "h1 { color: hotpink; }" > style.css',
        'echo "<h1>Shop</h1>" > index.html',
        "git add .",
        'git commit -m "Add page and styles"',
        'echo "h1 { color: crimson; }" > style.css',
        'edit index.html "<p>Half-written idea</p>"',
      ],
      goals: [
        goals.custom(
          "saw-staged",
          "Check the staged change (git diff --staged)",
          ({ commands }) => commands.some((command) => /^git diff\s+(--staged|--cached)\b/.test(command.trim())),
          true,
        ),
        goals.focusedCommit(["style.css"], "Commit style.css only"),
        goals.custom(
          "kept-unstaged",
          "index.html is still unsaved",
          ({ state, initial }) => state.workdir["index.html"] === initial.workdir["index.html"] && headTree(state)["index.html"] !== state.workdir["index.html"],
        ),
      ],
      hints: ["Stage just the one file: git add style.css", 'Then look at what is staged (git diff --staged) and commit: git commit -m "Crimson headings"'],
      solution: ["git add style.css", "git diff --staged", 'git commit -m "Crimson headings"'],
      xp: 40,
    },
    {
      id: "unstage-all",
      title: "Unstage everything",
      phase: "practice",
      mission: "You staged four files in one go, but none of them are ready. Empty the staging area in one command — the files themselves stay exactly as they are.",
      concept: {
        title: "git reset HEAD",
        body: "Plain git reset (or git reset HEAD) puts the staging area back to the last commit and leaves your files alone. It's git restore --staged for everything at once.",
      },
      setup: [...initial, 'echo "a()" > a.js', 'echo "b()" > b.js', 'echo "c()" > c.js', 'echo "d()" > d.js', "git add ."],
      goals: [
        goals.custom("nothing-staged", "Nothing is staged any more", ({ state }) => computeStatus(state).staged.length === 0),
        goals.custom(
          "files-kept",
          "All four files are still in your folder",
          ({ state }) => ["a.js", "b.js", "c.js", "d.js"].every((path) => Object.hasOwn(state.workdir, path)),
        ),
      ],
      hints: ["One command empties the staging area without touching your files.", "Type: git reset HEAD (plain git reset does the same)"],
      solution: ["git reset HEAD"],
      xp: 55,
    },
    {
      id: "compare-commits",
      title: "Compare two commits",
      phase: "practice",
      mission: "Before undoing anything, see what actually changed between the release two commits ago and now.",
      concept: {
        title: "git diff <old>..<new>",
        body: "git diff also compares two commits: git diff HEAD~2..HEAD shows everything that changed between them. Useful for checking what a rollback would throw away.",
      },
      setup: [
        ...initial,
        'echo "shop()" > shop.js',
        "git add .",
        'git commit -m "Add shop"',
        'edit shop.js "cart()"',
        'git commit -am "Add cart"',
        'edit shop.js "checkout()"',
        'git commit -am "Add checkout"',
      ],
      goals: [
        goals.custom(
          "compared",
          "Compare the last two commits with the older one",
          ({ commands }) => commands.some((command) => /^git diff\s+\S*(\.\.|\s)\S+/.test(command.trim())),
          true,
        ),
      ],
      hints: ["git diff takes two commits, separated by .. or a space.", "Type: git diff HEAD~2..HEAD"],
      solution: ["git diff HEAD~2..HEAD"],
      xp: 55,
    },
    {
      id: "amend",
      title: "Fix a commit message",
      mission: "You just committed with the message 'Add lgoin page'. Oops! Replace that last commit with one whose message is 'Add login page' — without adding an extra commit.",
      concept: {
        title: "git commit --amend",
        body: "--amend replaces your most recent commit with a new one. Only amend commits you haven't shared with anyone yet.",
      },
      setup: [...initial, 'echo "<form>Log in</form>" > login.html', "git add .", 'git commit -m "Add lgoin page"'],
      goals: [goals.tipMessage("main", "Add login page", "The last commit says 'Add login page'"), goals.exactCommitCount("main", 2, "Still exactly 2 commits")],
      hints: ["You don't want a new commit — you want to replace the last one.", 'Type: git commit --amend -m "Add login page"'],
      solution: ['git commit --amend -m "Add login page"'],
      xp: 55,
    },
    {
      id: "forgotten-file",
      title: "Forgot a file",
      phase: "practice",
      mission: "You committed 'Add login page' but forgot login.css. Put login.css into that same commit instead of making a new one.",
      concept: {
        title: "Amend with files",
        body: "Anything you stage before git commit --amend is added into the last commit. --no-edit keeps its message.",
      },
      setup: [...initial, 'echo "<form>Log in</form>" > login.html', 'echo "form { margin: 0; }" > login.css', "git add login.html", 'git commit -m "Add login page"'],
      goals: [
        goals.committedFile("login.css", "login.css is in the last commit"),
        goals.tipMessage("main", "Add login page", "The message is still 'Add login page'"),
        goals.exactCommitCount("main", 2, "Still exactly 2 commits"),
      ],
      hints: ["Stage the forgotten file first: git add login.css", "Fold it into the last commit: git commit --amend --no-edit"],
      solution: ["git add login.css", "git commit --amend --no-edit"],
      xp: 55,
    },
    {
      id: "soft-reset",
      title: "Undo a commit, keep the work",
      mission: "You committed half-finished work too early. Undo that commit, but keep all its changes staged so nothing is lost.",
      concept: {
        title: "git reset --soft",
        body: "reset moves your branch back to an earlier commit. With --soft, the changes from the undone commit stay staged, ready to commit again.",
      },
      setup: [...initial, 'echo "search()" > search.js', "git add .", 'git commit -m "WIP: half-done search"'],
      goals: [goals.tipMessage("main", "Initial commit", "main is back on 'Initial commit'"), goals.staged("search.js", "search.js is still staged")],
      hints: ["Move main back one commit. Which reset mode keeps changes staged?", "Type: git reset --soft HEAD~1"],
      solution: ["git reset --soft HEAD~1"],
      xp: 60,
    },
    {
      id: "rewind",
      title: "Rewind completely",
      mission: "Last night you made two commits that broke the shop, and nobody has seen them. Move main back to 'Initial commit' and throw those broken changes away completely.",
      concept: {
        title: "git reset --hard",
        body: "--hard moves the branch back AND resets your files to match. Use it when you're sure you want to throw work away.",
      },
      setup: [...initial, 'echo "broken()" > app.js', "git add .", 'git commit -m "WIP: experiment"', 'edit app.js "more broken()"', 'git commit -am "WIP: still broken"'],
      goals: [goals.tipMessage("main", "Initial commit", "main is back on 'Initial commit'"), goals.cleanTree("No broken changes left behind")],
      hints: ["You need to go back two commits (HEAD~2) and also reset the files.", "Type: git reset --hard HEAD~2"],
      solution: ["git reset --hard HEAD~2"],
      xp: 60,
    },
    {
      id: "safe-undo",
      title: "Undo without rewriting",
      mission: "The commit 'Add buggy popup' was shared with the whole team yesterday, so rewriting history is off the table. Undo it with a NEW commit, keeping the later 'Add blog' commit.",
      concept: {
        title: "git revert",
        body: "revert makes a new commit that does the opposite of an old one. History only grows, so it's safe for commits other people already have.",
      },
      setup: [...initial, "echo \"alert('SPAM')\" > popup.js", "git add .", 'git commit -m "Add buggy popup"', 'echo "<h1>Blog</h1>" > blog.html', "git add .", 'git commit -m "Add blog"'],
      goals: [
        goals.tipMessage("main", 'Revert "Add buggy popup"', "Add a commit that reverts the popup"),
        goals.absentFromHead("popup.js", "popup.js is gone"),
        goals.committedFile("blog.html", "blog.html is still there"),
      ],
      hints: ["The buggy commit is one before the latest one: HEAD~1.", "Type: git revert HEAD~1"],
      solution: ["git revert HEAD~1"],
      xp: 65,
    },
    {
      id: "revert-older",
      title: "Undo something older",
      phase: "practice",
      mission: "Three commits ago someone added a tracking pixel the team now wants gone. Two good commits came after it, so keep those and undo just that one — by its own id.",
      concept: {
        title: "Reverting by id",
        body: "revert takes any commit, not just the last one. Find the id with git log, then revert it — Git works out the opposite change for you.",
      },
      setup: [
        ...initial,
        'echo "trackEverything()" > tracker.js',
        "git add .",
        'git commit -m "Add tracking pixel"',
        'echo "<h1>Help</h1>" > help.html',
        "git add .",
        'git commit -m "Add help page"',
        'echo "<h1>Jobs</h1>" > jobs.html',
        "git add .",
        'git commit -m "Add jobs page"',
      ],
      goals: [
        goals.absentFromHead("tracker.js", "tracker.js is gone"),
        goals.committedFile("help.html", "The help page is still there"),
        goals.committedFile("jobs.html", "…and so is the jobs page"),
        goals.custom("kept-history", "Nothing was rewritten — a new commit undid it", ({ state, initial: start }) => {
          const tip = state.branches.main;
          return !!tip && Object.keys(state.commits).length > Object.keys(start.commits).length && !!start.branches.main && Object.hasOwn(state.commits, start.branches.main);
        }),
      ],
      hints: ["git log --oneline shows the ids. The tracking commit is three back: HEAD~2.", "Revert it by id or by position: git revert HEAD~2"],
      solution: ["git log --oneline", "git revert {{rev:HEAD~2}}"],
      xp: 65,
    },
    {
      id: "reflog-rescue",
      title: "Rescue lost work",
      mission: "Someone ran git reset --hard and the 'Important work' commit disappeared from main. It isn't really gone — find it in the reflog and bring main back to it.",
      concept: {
        title: "git reflog",
        body: "The reflog is a diary of everywhere HEAD has been. Commits 'lost' by a reset are still listed there, so you can jump back to them.",
      },
      setup: [...initial, 'echo "important()" > important.js', "git add .", 'git commit -m "Important work"', "git reset --hard HEAD~1"],
      goals: [goals.containsMessage("main", "Important work", "main has 'Important work' again"), goals.committedFile("important.js", "important.js is back")],
      hints: ["git reflog shows every place HEAD has been. HEAD@{1} is where it was one step ago.", "Type: git reset --hard HEAD@{1}"],
      solution: ["git reflog", "git reset --hard HEAD@{1}"],
      xp: 70,
    },
    {
      id: "unstage-one-of-two",
      title: "Unstage just one",
      phase: "practice",
      mission: "Both app.js and draft.txt are staged, but the draft isn't ready. Take the draft out of the staging area and commit only app.js.",
      concept: {
        title: "Staging is a choice",
        body: "The staging area lets you split messy work into tidy commits: unstage what isn't ready, commit what is, and carry on.",
      },
      setup: [...initial, 'echo "boot()" > app.js', 'echo "half an idea" > draft.txt', "git add ."],
      goals: [
        goals.focusedCommit(["app.js"], "Commit app.js on its own"),
        goals.untrackedOnDisk("draft.txt", "draft.txt is left out"),
        goals.custom("draft-kept", "…but still on disk", ({ state }) => Object.hasOwn(state.workdir, "draft.txt")),
      ],
      hints: ["Take it out of the staging area: git restore --staged draft.txt", "Then commit what is left: git commit -m \"Add app\""],
      solution: ["git restore --staged draft.txt", 'git commit -m "Add app"'],
      xp: 55,
    },
    {
      id: "amend-again",
      title: "Tidy the message",
      phase: "practice",
      mission: "Your last commit says 'stuff'. Give it a message that actually explains the change — without creating a second commit.",
      concept: {
        title: "Amend is for the last commit",
        body: "--amend swaps the newest commit for a better one. Perfect for a bad message, as long as nobody else has it yet.",
      },
      setup: [...initial, 'echo "checkout()" > checkout.js', "git add .", 'git commit -m "stuff"'],
      goals: [
        goals.tipMessage("main", "Add checkout page", "The last commit explains itself"),
        goals.exactCommitCount("main", 2, "Still exactly 2 commits"),
        goals.committedFile("checkout.js", "checkout.js is still in it"),
      ],
      hints: ["You want to replace the last commit, not add one.", 'Type: git commit --amend -m "Add checkout page"'],
      solution: ['git commit --amend -m "Add checkout page"'],
      xp: 55,
    },
    {
      id: "mixed-reset",
      title: "Undo a commit, keep the files",
      phase: "practice",
      mission: "The last commit mixed two unrelated changes. Undo the commit itself but keep both files exactly as they are on disk, ready to be staged separately.",
      concept: {
        title: "git reset (mixed)",
        body: "Plain git reset <commit> moves the branch back and empties the staging area, but never touches your files — the changes are yours to re-stage as you like.",
      },
      setup: [...initial, 'echo "nav()" > nav.js', 'echo "footer()" > footer.js', "git add .", 'git commit -m "Nav and footer together"'],
      goals: [
        goals.tipMessage("main", "Initial commit", "main is back on 'Initial commit'"),
        goals.custom("nothing-staged", "Nothing is staged", ({ state }) => computeStatus(state).staged.length === 0),
        goals.custom(
          "files-kept",
          "Both files are still on disk",
          ({ state }) => Object.hasOwn(state.workdir, "nav.js") && Object.hasOwn(state.workdir, "footer.js"),
        ),
      ],
      hints: ["Which reset mode moves the branch but leaves files alone? The default one.", "Type: git reset HEAD~1"],
      solution: ["git reset HEAD~1"],
      xp: 60,
    },
    {
      id: "look-then-revert",
      title: "Look before you undo",
      phase: "practice",
      mission: "A commit called 'Add tracking banner' upset everyone. Open it to see exactly what it changed, then undo it with a new commit — the banner commit stays in history.",
      concept: {
        title: "Read, then undo",
        body: "git show <commit> prints everything a commit changed. Checking first means you revert the right one — and revert never rewrites what's already shared.",
      },
      setup: [
        ...initial,
        'echo "banner()" > banner.js',
        "git add .",
        'git commit -m "Add tracking banner"',
        'echo "<h1>Shop</h1>" > shop.html',
        "git add .",
        'git commit -m "Add shop page"',
      ],
      goals: [
        goals.absentFromHead("banner.js", "The banner file is gone"),
        goals.committedFile("shop.html", "The shop page is still there"),
        goals.custom("nothing-rewritten", "Nothing was rewritten — a new commit undid it", ({ state, initial: start }) => {
          const oldTip = start.branches.main;
          return !!oldTip && Object.hasOwn(state.commits, oldTip) && Object.keys(state.commits).length > Object.keys(start.commits).length;
        }),
      ],
      hints: ["See what it did: git show HEAD~1", "Then undo it safely: git revert HEAD~1"],
      solution: ["git show HEAD~1", "git revert HEAD~1"],
      xp: 65,
    },
    {
      id: "reflog-again",
      title: "Rescue a deleted branch",
      phase: "practice",
      mission: "You deleted the experiment branch with -D, then realised its commit was worth keeping. Find where HEAD has been and bring that work back onto main.",
      concept: {
        title: "The reflog remembers",
        body: "Deleting a branch only removes a label; the commit is still there. git reflog shows every position HEAD has had, so you can merge or reset back to it.",
      },
      setup: [
        ...initial,
        "git switch -c experiment",
        'echo "brilliant()" > brilliant.js',
        "git add .",
        'git commit -m "Brilliant idea"',
        "git switch main",
        "git branch -D experiment",
      ],
      goals: [
        goals.containsMessage("main", "Brilliant idea", "main has the brilliant commit"),
        goals.committedFile("brilliant.js", "brilliant.js is back"),
      ],
      hints: ["Find where HEAD has been: git reflog", "Then bring it in: git merge HEAD@{1} (or git reset --hard HEAD@{1} if main has nothing of its own)"],
      solution: ["git reflog", "git merge HEAD@{1}"],
      xp: 75,
    },
    {
      id: "check-staging",
      title: "Check the staging area first",
      phase: "practice",
      mission: "Three files are staged and one of them — notes.txt — shouldn't be. Look at what's staged, take the note back out, and commit the rest.",
      concept: {
        title: "Look, then fix",
        body: "git diff --staged is the last check before a commit. Anything that shouldn't be there comes out with git restore --staged, and the rest is committed.",
      },
      setup: [...initial, 'echo "nav()" > nav.js', 'echo "footer()" > footer.js', 'echo "remember milk" > notes.txt', "git add ."],
      goals: [
        goals.committedFile("nav.js", "nav.js is committed"),
        goals.committedFile("footer.js", "…and footer.js"),
        goals.untrackedOnDisk("notes.txt", "notes.txt is left out"),
        goals.custom("note-kept", "…but still on disk", ({ state }) => Object.hasOwn(state.workdir, "notes.txt")),
      ],
      hints: ["See exactly what's staged: git diff --staged", 'Then take the note out (git restore --staged notes.txt) and commit: git commit -m "Add nav and footer"'],
      solution: ["git diff --staged", "git restore --staged notes.txt", 'git commit -m "Add nav and footer"'],
      xp: 60,
    },
    {
      id: "checkpoint-undo",
      title: "Checkpoint: clean up the mess",
      phase: "checkpoint",
      mission:
        "Three problems at once: secrets.txt was staged by mistake, README.md has an edit you don't want, and app.js is genuinely ready. Sort it out — keep the secret file on disk but out of Git, throw the README edit away, and commit app.js on its own.",
      concept: {
        title: "Choosing the right undo",
        body: "restore --staged takes something out of the staging area, plain restore throws away an edit on disk, and commit saves what's left. Pick the tool that matches the mistake.",
      },
      setup: [
        ...initial,
        "echo \"boot()\" > app.js",
        'echo "api-key-1234" > secrets.txt',
        "git add .",
        'echo "delete all the docs" > README.md',
      ],
      goals: [
        goals.untrackedOnDisk("secrets.txt", "secrets.txt is out of the staging area"),
        goals.custom("secret-kept", "…but still on disk", ({ state }) => Object.hasOwn(state.workdir, "secrets.txt")),
        goals.custom("readme-back", "The README edit is thrown away", ({ state }) => state.initialized && state.workdir["README.md"] === headTree(state)["README.md"]),
        goals.focusedCommit(["app.js"], "app.js is committed on its own"),
      ],
      hints: [
        "Take the secret out of the staging area first: git restore --staged secrets.txt",
        "Throw away the README edit: git restore README.md",
        'Then commit what is left: git commit -m "Add app"',
      ],
      solution: ["git restore --staged secrets.txt", "git restore README.md", 'git commit -m "Add app"'],
      xp: 80,
    },
  ],
});
