import type { SandboxPreset } from "./types";

/** Starting points for free play in the sandbox. Add one by appending to this list. */
export const sandboxPresets: readonly SandboxPreset[] = [
  {
    id: "fresh-project",
    title: "Fresh project",
    emoji: "🌱",
    description: "A few files that aren't in Git yet.",
    setup: ['echo "# My Project" > README.md', 'echo "<h1>Hi</h1>" > index.html', 'echo "body { margin: 0; }" > style.css'],
  },
  {
    id: "history",
    title: "Some history",
    emoji: "📚",
    description: "A repository with a few commits on main.",
    setup: [
      'echo "# My Project" > README.md',
      "git init",
      "git add .",
      'git commit -m "Initial commit"',
      'echo "<h1>Hi</h1>" > index.html',
      "git add .",
      'git commit -m "Add homepage"',
      'echo "body { margin: 0; }" > style.css',
      "git add .",
      'git commit -m "Add styles"',
    ],
  },
  {
    id: "diverged",
    title: "Diverged branches",
    emoji: "🌿",
    description: "main and feature both have new commits. Try merge vs rebase!",
    setup: [
      'echo "# My Project" > README.md',
      "git init",
      "git add .",
      'git commit -m "Initial commit"',
      "git switch -c feature",
      'echo "login()" > login.js',
      "git add .",
      'git commit -m "Add login"',
      'edit login.js "logout()"',
      'git commit -am "Add logout"',
      "git switch main",
      'echo "<h1>Docs</h1>" > docs.html',
      "git add .",
      'git commit -m "Add docs"',
    ],
  },
  {
    id: "team-project",
    title: "Team project",
    emoji: "☁️",
    description: "A cloned GitHub repo. Try server commit to play a teammate, then fetch, pull and push.",
    setup: [
      "server create https://github.com/team/project",
      'server commit https://github.com/team/project "Initial commit" --file README.md --content "# Project"',
      'server commit https://github.com/team/project "Add homepage" --file index.html --content "<h1>Hi</h1>"',
      "git clone https://github.com/team/project",
    ],
  },
  {
    id: "conflict",
    title: "Conflict waiting to happen",
    emoji: "💥",
    description: "Both branches edited the same line. Run git merge feature.",
    setup: [
      'echo "color = blue" > config.txt',
      "git init",
      "git add .",
      'git commit -m "Initial config"',
      "git switch -c feature",
      'echo "color = green" > config.txt',
      'git commit -am "Go green"',
      "git switch main",
      'echo "color = red" > config.txt',
      'git commit -am "Go red"',
    ],
  },
];
