import { mkdirSync, writeFileSync } from "node:fs";
import { test } from "vitest";
import { curriculum, levelPar, levelSolution, phaseOf } from "@/content";

/** Rewrites documentation/curriculum.md from the content itself, so the reference list can never drift. */
test("write documentation/curriculum.md", () => {
  const label = { learn: "Learn", practice: "Practice", checkpoint: "Checkpoint" } as const;
  const rows: string[] = [];
  const sections: string[] = [];

  curriculum.topics.forEach((topic, topicIndex) => {
    sections.push(`\n## Topic ${topicIndex + 1} — ${topic.emoji} ${topic.title}\n`, `_${topic.tagline}_ · ${topic.levels.length} questions\n`);
    for (const entry of curriculum.levelsOf(topic.id)) {
      const { level, index, number } = entry;
      const kind = label[phaseOf(level)];
      sections.push(
        `### ${index + 1}. ${level.title}  \n`,
        `- **Kind:** ${kind} · **id:** \`${level.id}\` · **position in topic:** ${number} of ${topic.levels.length} · **XP:** ${level.xp} · **Par:** ${levelPar(level)}`,
        `- **Teaches:** ${level.concept.title} — ${level.concept.body}`,
        `- **Question:** ${level.mission}`,
        `- **Goals (checked as state, not as commands):** ${level.goals.map((goal) => goal.label).join(" · ")}`,
        `- **One solution:** ${levelSolution(level).map((command) => `\`${command}\``).join(" → ")}`,
        "",
      );
      rows.push(`| ${index + 1} | ${topic.title} | ${level.title} | ${kind} | ${level.concept.title} |`);
    }
  });

  const header = [
    "# Curriculum — every topic and question",
    "",
    "> Generated by `npm run docs` from `src/content/topics/*.ts`. Don't edit by hand.",
    "",
    `**${curriculum.levels.length} questions in ${curriculum.topics.length} topics**, in topic order: ${curriculum.topics.map((topic) => topic.title.toLowerCase()).join(" → ")}.`,
    "",
    "Every question is solved with git commands only, and judged by the repository state you reach — the solutions below are one route among several. See [learning-order.md](learning-order.md#how-levels-are-judged) and [adding-content.md](adding-content.md).",
    "",
    "| # | Topic | Question | Kind | Teaches |",
    "| --- | --- | --- | --- | --- |",
    ...rows,
  ].join("\n");

  mkdirSync("documentation", { recursive: true });
  writeFileSync("documentation/curriculum.md", `${header}\n${sections.join("\n")}\n`);
});
